# Site settings
title: Roy van de Water
description: >
  Roy works at Octoblu Inc. to help bring about the rise of the machines.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://royvandewater.com" # the base hostname & protocol for your site
twitter_username: royvandewater
github_username:  royvandewater

# Build settings
markdown: kramdown
